/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaithIndexRouteImport } from './routes/faith/index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as FaithNameRouteImport } from './routes/faith/$name'
import { Route as EventsDetailsRouteImport } from './routes/events/details'
import { Route as AboutNameRouteImport } from './routes/about/$name'
import { Route as EventsIndexRouteImport } from './routes/events/index.'
import { Route as FaithProjektIndexRouteImport } from './routes/faith/projekt/index'
import { Route as CommunitiesWesuweIndexRouteImport } from './routes/communities/wesuwe/index'
import { Route as CommunitiesTinnenIndexRouteImport } from './routes/communities/tinnen/index'
import { Route as CommunitiesHarenIndexRouteImport } from './routes/communities/haren/index'
import { Route as CommunitiesEmmelnIndexRouteImport } from './routes/communities/emmeln/index'
import { Route as CommunitiesAltharenIndexRouteImport } from './routes/communities/altharen/index'
import { Route as PostDetailsIdRouteImport } from './routes/post/details/$id'
import { Route as FaithProjektNameRouteImport } from './routes/faith/projekt/$name'
import { Route as CommunitiesWesuweNameRouteImport } from './routes/communities/wesuwe/$name'
import { Route as CommunitiesTinnenNameRouteImport } from './routes/communities/tinnen/$name'
import { Route as CommunitiesHarenNameRouteImport } from './routes/communities/haren/$name'
import { Route as CommunitiesEmmelnNameRouteImport } from './routes/communities/emmeln/$name'
import { Route as CommunitiesAltharenNameRouteImport } from './routes/communities/altharen/$name'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaithIndexRoute = FaithIndexRouteImport.update({
  id: '/faith/',
  path: '/faith/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaithNameRoute = FaithNameRouteImport.update({
  id: '/faith/$name',
  path: '/faith/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsDetailsRoute = EventsDetailsRouteImport.update({
  id: '/events/details',
  path: '/events/details',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutNameRoute = AboutNameRouteImport.update({
  id: '/about/$name',
  path: '/about/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/index/',
  path: '/events/index/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaithProjektIndexRoute = FaithProjektIndexRouteImport.update({
  id: '/faith/projekt/',
  path: '/faith/projekt/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesWesuweIndexRoute = CommunitiesWesuweIndexRouteImport.update({
  id: '/communities/wesuwe/',
  path: '/communities/wesuwe/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesTinnenIndexRoute = CommunitiesTinnenIndexRouteImport.update({
  id: '/communities/tinnen/',
  path: '/communities/tinnen/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesHarenIndexRoute = CommunitiesHarenIndexRouteImport.update({
  id: '/communities/haren/',
  path: '/communities/haren/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesEmmelnIndexRoute = CommunitiesEmmelnIndexRouteImport.update({
  id: '/communities/emmeln/',
  path: '/communities/emmeln/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesAltharenIndexRoute =
  CommunitiesAltharenIndexRouteImport.update({
    id: '/communities/altharen/',
    path: '/communities/altharen/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostDetailsIdRoute = PostDetailsIdRouteImport.update({
  id: '/post/details/$id',
  path: '/post/details/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FaithProjektNameRoute = FaithProjektNameRouteImport.update({
  id: '/faith/projekt/$name',
  path: '/faith/projekt/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesWesuweNameRoute = CommunitiesWesuweNameRouteImport.update({
  id: '/communities/wesuwe/$name',
  path: '/communities/wesuwe/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesTinnenNameRoute = CommunitiesTinnenNameRouteImport.update({
  id: '/communities/tinnen/$name',
  path: '/communities/tinnen/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesHarenNameRoute = CommunitiesHarenNameRouteImport.update({
  id: '/communities/haren/$name',
  path: '/communities/haren/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesEmmelnNameRoute = CommunitiesEmmelnNameRouteImport.update({
  id: '/communities/emmeln/$name',
  path: '/communities/emmeln/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesAltharenNameRoute = CommunitiesAltharenNameRouteImport.update({
  id: '/communities/altharen/$name',
  path: '/communities/altharen/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/team': typeof TeamRoute
  '/about/$name': typeof AboutNameRoute
  '/events/details': typeof EventsDetailsRoute
  '/faith/$name': typeof FaithNameRoute
  '/about/': typeof AboutIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/faith/': typeof FaithIndexRoute
  '/communities/altharen/$name': typeof CommunitiesAltharenNameRoute
  '/communities/emmeln/$name': typeof CommunitiesEmmelnNameRoute
  '/communities/haren/$name': typeof CommunitiesHarenNameRoute
  '/communities/tinnen/$name': typeof CommunitiesTinnenNameRoute
  '/communities/wesuwe/$name': typeof CommunitiesWesuweNameRoute
  '/faith/projekt/$name': typeof FaithProjektNameRoute
  '/post/details/$id': typeof PostDetailsIdRoute
  '/communities/altharen/': typeof CommunitiesAltharenIndexRoute
  '/communities/emmeln/': typeof CommunitiesEmmelnIndexRoute
  '/communities/haren/': typeof CommunitiesHarenIndexRoute
  '/communities/tinnen/': typeof CommunitiesTinnenIndexRoute
  '/communities/wesuwe/': typeof CommunitiesWesuweIndexRoute
  '/events/index/': typeof EventsIndexRoute
  '/faith/projekt/': typeof FaithProjektIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/team': typeof TeamRoute
  '/about/$name': typeof AboutNameRoute
  '/events/details': typeof EventsDetailsRoute
  '/faith/$name': typeof FaithNameRoute
  '/about': typeof AboutIndexRoute
  '/communities': typeof CommunitiesIndexRoute
  '/faith': typeof FaithIndexRoute
  '/communities/altharen/$name': typeof CommunitiesAltharenNameRoute
  '/communities/emmeln/$name': typeof CommunitiesEmmelnNameRoute
  '/communities/haren/$name': typeof CommunitiesHarenNameRoute
  '/communities/tinnen/$name': typeof CommunitiesTinnenNameRoute
  '/communities/wesuwe/$name': typeof CommunitiesWesuweNameRoute
  '/faith/projekt/$name': typeof FaithProjektNameRoute
  '/post/details/$id': typeof PostDetailsIdRoute
  '/communities/altharen': typeof CommunitiesAltharenIndexRoute
  '/communities/emmeln': typeof CommunitiesEmmelnIndexRoute
  '/communities/haren': typeof CommunitiesHarenIndexRoute
  '/communities/tinnen': typeof CommunitiesTinnenIndexRoute
  '/communities/wesuwe': typeof CommunitiesWesuweIndexRoute
  '/events/index': typeof EventsIndexRoute
  '/faith/projekt': typeof FaithProjektIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/team': typeof TeamRoute
  '/about/$name': typeof AboutNameRoute
  '/events/details': typeof EventsDetailsRoute
  '/faith/$name': typeof FaithNameRoute
  '/about/': typeof AboutIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/faith/': typeof FaithIndexRoute
  '/communities/altharen/$name': typeof CommunitiesAltharenNameRoute
  '/communities/emmeln/$name': typeof CommunitiesEmmelnNameRoute
  '/communities/haren/$name': typeof CommunitiesHarenNameRoute
  '/communities/tinnen/$name': typeof CommunitiesTinnenNameRoute
  '/communities/wesuwe/$name': typeof CommunitiesWesuweNameRoute
  '/faith/projekt/$name': typeof FaithProjektNameRoute
  '/post/details/$id': typeof PostDetailsIdRoute
  '/communities/altharen/': typeof CommunitiesAltharenIndexRoute
  '/communities/emmeln/': typeof CommunitiesEmmelnIndexRoute
  '/communities/haren/': typeof CommunitiesHarenIndexRoute
  '/communities/tinnen/': typeof CommunitiesTinnenIndexRoute
  '/communities/wesuwe/': typeof CommunitiesWesuweIndexRoute
  '/events/index/': typeof EventsIndexRoute
  '/faith/projekt/': typeof FaithProjektIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/datenschutz'
    | '/impressum'
    | '/team'
    | '/about/$name'
    | '/events/details'
    | '/faith/$name'
    | '/about/'
    | '/communities/'
    | '/faith/'
    | '/communities/altharen/$name'
    | '/communities/emmeln/$name'
    | '/communities/haren/$name'
    | '/communities/tinnen/$name'
    | '/communities/wesuwe/$name'
    | '/faith/projekt/$name'
    | '/post/details/$id'
    | '/communities/altharen/'
    | '/communities/emmeln/'
    | '/communities/haren/'
    | '/communities/tinnen/'
    | '/communities/wesuwe/'
    | '/events/index/'
    | '/faith/projekt/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/datenschutz'
    | '/impressum'
    | '/team'
    | '/about/$name'
    | '/events/details'
    | '/faith/$name'
    | '/about'
    | '/communities'
    | '/faith'
    | '/communities/altharen/$name'
    | '/communities/emmeln/$name'
    | '/communities/haren/$name'
    | '/communities/tinnen/$name'
    | '/communities/wesuwe/$name'
    | '/faith/projekt/$name'
    | '/post/details/$id'
    | '/communities/altharen'
    | '/communities/emmeln'
    | '/communities/haren'
    | '/communities/tinnen'
    | '/communities/wesuwe'
    | '/events/index'
    | '/faith/projekt'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/datenschutz'
    | '/impressum'
    | '/team'
    | '/about/$name'
    | '/events/details'
    | '/faith/$name'
    | '/about/'
    | '/communities/'
    | '/faith/'
    | '/communities/altharen/$name'
    | '/communities/emmeln/$name'
    | '/communities/haren/$name'
    | '/communities/tinnen/$name'
    | '/communities/wesuwe/$name'
    | '/faith/projekt/$name'
    | '/post/details/$id'
    | '/communities/altharen/'
    | '/communities/emmeln/'
    | '/communities/haren/'
    | '/communities/tinnen/'
    | '/communities/wesuwe/'
    | '/events/index/'
    | '/faith/projekt/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  TeamRoute: typeof TeamRoute
  AboutNameRoute: typeof AboutNameRoute
  EventsDetailsRoute: typeof EventsDetailsRoute
  FaithNameRoute: typeof FaithNameRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  FaithIndexRoute: typeof FaithIndexRoute
  CommunitiesAltharenNameRoute: typeof CommunitiesAltharenNameRoute
  CommunitiesEmmelnNameRoute: typeof CommunitiesEmmelnNameRoute
  CommunitiesHarenNameRoute: typeof CommunitiesHarenNameRoute
  CommunitiesTinnenNameRoute: typeof CommunitiesTinnenNameRoute
  CommunitiesWesuweNameRoute: typeof CommunitiesWesuweNameRoute
  FaithProjektNameRoute: typeof FaithProjektNameRoute
  PostDetailsIdRoute: typeof PostDetailsIdRoute
  CommunitiesAltharenIndexRoute: typeof CommunitiesAltharenIndexRoute
  CommunitiesEmmelnIndexRoute: typeof CommunitiesEmmelnIndexRoute
  CommunitiesHarenIndexRoute: typeof CommunitiesHarenIndexRoute
  CommunitiesTinnenIndexRoute: typeof CommunitiesTinnenIndexRoute
  CommunitiesWesuweIndexRoute: typeof CommunitiesWesuweIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  FaithProjektIndexRoute: typeof FaithProjektIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faith/': {
      id: '/faith/'
      path: '/faith'
      fullPath: '/faith/'
      preLoaderRoute: typeof FaithIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faith/$name': {
      id: '/faith/$name'
      path: '/faith/$name'
      fullPath: '/faith/$name'
      preLoaderRoute: typeof FaithNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/details': {
      id: '/events/details'
      path: '/events/details'
      fullPath: '/events/details'
      preLoaderRoute: typeof EventsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$name': {
      id: '/about/$name'
      path: '/about/$name'
      fullPath: '/about/$name'
      preLoaderRoute: typeof AboutNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/index/': {
      id: '/events/index/'
      path: '/events/index'
      fullPath: '/events/index/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faith/projekt/': {
      id: '/faith/projekt/'
      path: '/faith/projekt'
      fullPath: '/faith/projekt/'
      preLoaderRoute: typeof FaithProjektIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/wesuwe/': {
      id: '/communities/wesuwe/'
      path: '/communities/wesuwe'
      fullPath: '/communities/wesuwe/'
      preLoaderRoute: typeof CommunitiesWesuweIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/tinnen/': {
      id: '/communities/tinnen/'
      path: '/communities/tinnen'
      fullPath: '/communities/tinnen/'
      preLoaderRoute: typeof CommunitiesTinnenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/haren/': {
      id: '/communities/haren/'
      path: '/communities/haren'
      fullPath: '/communities/haren/'
      preLoaderRoute: typeof CommunitiesHarenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/emmeln/': {
      id: '/communities/emmeln/'
      path: '/communities/emmeln'
      fullPath: '/communities/emmeln/'
      preLoaderRoute: typeof CommunitiesEmmelnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/altharen/': {
      id: '/communities/altharen/'
      path: '/communities/altharen'
      fullPath: '/communities/altharen/'
      preLoaderRoute: typeof CommunitiesAltharenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/details/$id': {
      id: '/post/details/$id'
      path: '/post/details/$id'
      fullPath: '/post/details/$id'
      preLoaderRoute: typeof PostDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faith/projekt/$name': {
      id: '/faith/projekt/$name'
      path: '/faith/projekt/$name'
      fullPath: '/faith/projekt/$name'
      preLoaderRoute: typeof FaithProjektNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/wesuwe/$name': {
      id: '/communities/wesuwe/$name'
      path: '/communities/wesuwe/$name'
      fullPath: '/communities/wesuwe/$name'
      preLoaderRoute: typeof CommunitiesWesuweNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/tinnen/$name': {
      id: '/communities/tinnen/$name'
      path: '/communities/tinnen/$name'
      fullPath: '/communities/tinnen/$name'
      preLoaderRoute: typeof CommunitiesTinnenNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/haren/$name': {
      id: '/communities/haren/$name'
      path: '/communities/haren/$name'
      fullPath: '/communities/haren/$name'
      preLoaderRoute: typeof CommunitiesHarenNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/emmeln/$name': {
      id: '/communities/emmeln/$name'
      path: '/communities/emmeln/$name'
      fullPath: '/communities/emmeln/$name'
      preLoaderRoute: typeof CommunitiesEmmelnNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/altharen/$name': {
      id: '/communities/altharen/$name'
      path: '/communities/altharen/$name'
      fullPath: '/communities/altharen/$name'
      preLoaderRoute: typeof CommunitiesAltharenNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  TeamRoute: TeamRoute,
  AboutNameRoute: AboutNameRoute,
  EventsDetailsRoute: EventsDetailsRoute,
  FaithNameRoute: FaithNameRoute,
  AboutIndexRoute: AboutIndexRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  FaithIndexRoute: FaithIndexRoute,
  CommunitiesAltharenNameRoute: CommunitiesAltharenNameRoute,
  CommunitiesEmmelnNameRoute: CommunitiesEmmelnNameRoute,
  CommunitiesHarenNameRoute: CommunitiesHarenNameRoute,
  CommunitiesTinnenNameRoute: CommunitiesTinnenNameRoute,
  CommunitiesWesuweNameRoute: CommunitiesWesuweNameRoute,
  FaithProjektNameRoute: FaithProjektNameRoute,
  PostDetailsIdRoute: PostDetailsIdRoute,
  CommunitiesAltharenIndexRoute: CommunitiesAltharenIndexRoute,
  CommunitiesEmmelnIndexRoute: CommunitiesEmmelnIndexRoute,
  CommunitiesHarenIndexRoute: CommunitiesHarenIndexRoute,
  CommunitiesTinnenIndexRoute: CommunitiesTinnenIndexRoute,
  CommunitiesWesuweIndexRoute: CommunitiesWesuweIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  FaithProjektIndexRoute: FaithProjektIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
